spring.application.name=product
# sql properties
spring.datasource.url = jdbc:mysql://products.c1ss262cqtsf.ap-south-1.rds.amazonaws.com:3306/products?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username = admin
spring.datasource.password = password4567
server.port=8082
# hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
useSSL=false
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update