spring.application.name=product
# sql properties
spring.datasource.url = jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = LZ@$F%#@8&O&
server.port=8082
# hibernate properties


# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update